import type { Playlist, PlaylistWithTracks, Track } from "../shared/types";
import type { MusicProvider, MusicProviderCapabilities } from "./provider";

/**
 * DemoMusicProvider — a fully offline music source.
 *
 * The audio files are procedurally generated by `scripts/generate-demo-audio.mjs`
 * (synthesized drums + bass authored by this project — no licensing concerns),
 * so Pacer is legally free to tempo-shift them. Each track's BPM is known
 * exactly because we synthesized it.
 */

export const DEMO_TRACKS: Track[] = [
  {
    id: "demo-1",
    provider: "demo",
    providerTrackId: "demo-1",
    name: "Warmup Groove",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 120,
    metadata: { audioUrl: "/audio/demo-120.wav", loop: true, hue: 200 },
  },
  {
    id: "demo-2",
    provider: "demo",
    providerTrackId: "demo-2",
    name: "Steady State",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 140,
    metadata: { audioUrl: "/audio/demo-140.wav", loop: true, hue: 160 },
  },
  {
    id: "demo-3",
    provider: "demo",
    providerTrackId: "demo-3",
    name: "Cruise Control",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 150,
    metadata: { audioUrl: "/audio/demo-150.wav", loop: true, hue: 120 },
  },
  {
    id: "demo-4",
    provider: "demo",
    providerTrackId: "demo-4",
    name: "Tempo Runner",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 160,
    metadata: { audioUrl: "/audio/demo-160.wav", loop: true, hue: 40 },
  },
  {
    id: "demo-5",
    provider: "demo",
    providerTrackId: "demo-5",
    name: "Negative Split",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 170,
    metadata: { audioUrl: "/audio/demo-170.wav", loop: true, hue: 0 },
  },
  {
    id: "demo-6",
    provider: "demo",
    providerTrackId: "demo-6",
    name: "Kick Finish",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 180,
    metadata: { audioUrl: "/audio/demo-180.wav", loop: true, hue: 320 },
  },
  {
    id: "demo-7",
    provider: "demo",
    providerTrackId: "demo-7",
    name: "Half-Time Roller",
    artist: "Pacer Demo",
    artworkUrl: null,
    durationMs: 0,
    bpm: 82,
    metadata: { audioUrl: "/audio/demo-82.wav", loop: true, hue: 260 },
  },
];

export const DEMO_PLAYLIST: PlaylistWithTracks = {
  id: "demo-playlist",
  provider: "demo",
  providerPlaylistId: "demo-playlist",
  name: "Pacer Demo Mix",
  artworkUrl: null,
  trackCount: DEMO_TRACKS.length,
  tracks: DEMO_TRACKS,
};

export class DemoMusicProvider implements MusicProvider {
  readonly id = "demo" as const;
  readonly label = "Demo Mode";
  readonly capabilities: MusicProviderCapabilities = {
    bpmMetadata: true,
    playbackControl: true,
    tempoShift: true,
    limitations: [
      "Synthesized demo audio only — showcases the tempo engine, not your library.",
    ],
  };

  async isConnected(): Promise<boolean> {
    return true;
  }

  async getPlaylists(): Promise<Playlist[]> {
    const { tracks: _tracks, ...playlist } = DEMO_PLAYLIST;
    return [playlist];
  }

  async getPlaylist(): Promise<PlaylistWithTracks> {
    return DEMO_PLAYLIST;
  }

  async getTracks(): Promise<Track[]> {
    return DEMO_TRACKS;
  }
}
